# Use postgres/example user/password credentials
version: "3.1"
volumes:
  postgres_data:
    driver: local
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hana
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgres/hana/data
